### ISSUE TITLE
Is there any way that I can get the PDF of the paper now?

### ISSUE THREAD

**Issue by sdmms1** [ruixiao24/onefi#1]
Hi, I'm a student from SUSTech and have been attracted by your amazing work. Is there any way that I can get the paper and have a read before the start of SenSys 2021?

**Comment by OnePl3** [comment]
Hello, I would like to ask you the train_data.npy of your project, can you provide it for study?

**Comment by ruixiao24** [comment]
Sorry for the very late reply.  I think you have already got the paper. If not, the paper is also available at https://ruixiao24.github.io/files/rui_onefi.pdf.
