### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by Ma-Zijing** [ruixiao24/onefi#4]
I really wonder if the authors have run this prototype. It seems this prototype cannot run even with given csi data. Moreover, in my opinion, this project is far behind "prototype", in fact, the form of code is too awful.

**Comment by ruixiao24** [comment]
Hi bigMaxM,

We are sorry for your bad reproduction experience. Therfore, we have made the following change:
- We updated the usage guide in our readme file. 
- We rerun our code to ensure its correctness.

Please leave your traceback output so that we could identify where the issue is.
Thank you for your comments.

Hope this helps, 
Rui

**Comment by Ma-Zijing** [comment]
Thank you for your replies, ruixiao. First I feel sorry for my abrupt comments before, there is no doubt oneFi is a fantastic work in wireless sensing.

I will try to reproduce oneFi again after the update. I will share my traceback if it still doesn't work.

Thanks.

**Comment by XiaoChen-NPU** [comment]
Dear author, OneFi is a great work in the field of wireless perception. I am trying to reproduce this work. In the process of promoting it, I have encountered several problems and would like to ask for your help:

1. After carefully reading the paper and Readme file, I was very confused about the file naming format rules of the original CSI data input in the virtual gesture generation stage, such as the meaning of each digit in the "1-1-1-1-r1.dat" file in the example. It would also be nice to open source the original CSI dataset.

2. When executing compute_velocity_distribution.m file, do we have to extract the speed distribution information from CSI data of four receivers at a time? If there are many gesture data, how should we integrate and extract it into the.npy file

**Comment by elegantCai** [comment]
Dear author，  
        I have read the paper of OneFi and it makes me learn a lot. Now I am trying to reproduce this work. Could you open source the dataset of OneFi? I'd appreciate so much if you can open source it!
        Wish you have a good day!
